### ISSUE TITLE
Sepolia Faucet not working since last 3 or 4 days

### ISSUE THREAD

**Issue by deepmineblocks** [pk910/PoWFaucet#278]
Faucet not working since last 3 or 4 days.

I regularly use this faucet to get testnet tokens but not working since last 3 or 4 days. After clicking the Start Mining button below error was thrown

![Screenshot 2024-08-22 140736](https://github.com/user-attachments/assets/46d93de1-88fc-443b-b513-e06f846d3e86)

**Comment by pk910** [comment]
Heya @deepmineblocks 
Thanks for reporting,  I've checked the sepolia faucet a moment ago and it seems to work fine..
But yea, something looks clearly broken on your side.

Can you check the developer console of your browser?
It's usually opened with F12. 
Please select the network tab in there and filter for a call with "startSession" in there:
![image](https://github.com/user-attachments/assets/b8a535c2-ce6c-4441-8c99-1039be4f7b59)

It seems like this call returns a HTTP error for you, which I'm not sure where it's coming from :D
Need to see the full error to see what's going on

**Comment by deepmineblocks** [comment]
Below is the response

I didn't understand why it is saying "504 Gateway Time-out".

![Screenshot 2024-08-22 200401](https://github.com/user-attachments/assets/ae672671-dc1b-4a5f-bee0-be2d704c6f48)

**Comment by deepmineblocks** [comment]
Any update on this ?

Its still not working for me

**Comment by deepmineblocks** [comment]
> **I'm getting this error response as described below once the startSession is falling:**
> 
> <title>504 Gateway Time-out</title>
> # 504 Gateway Time-out
> nginx/1.14.2

Same with me

**Comment by ran-noumena** [comment]
@pk910, it works again :)
![image](https://github.com/user-attachments/assets/97b6d3df-da40-49e7-adb3-5f3a3fd08c95)

**Comment by deepmineblocks** [comment]
Again started working

Thanks @pk910 

<details>
  <summary>startSession Response</summary>
  
```json
{
    "session": "135234e0-7536-4188-b584-5228b07153a7",
    "status": "running",
    "start": 1724918974,
    "tasks": [
        {
            "module": "pow",
            "name": "mining",
            "timeout": 1724962174
        }
    ],
    "balance": "0",
    "target": "0x818549Bd829b8F9Aa13Dc0dE9d3242Ee631a5438",
    "modules": {
        "pow": {
            "lastNonce": 0,
            "preImage": "BmkawJ7hlzU=",
            "shareCount": 0
        },
        "passport": {
            "nonce": 1,
            "score": 34.342999999999996,
            "factor": 2.6
        }
    }
}
```

**Comment by pk910** [comment]
Yea, I've restarted the process to enable the debug output :/
That made the problem disappear for you guys, but didn't actually solve anything.

I think it might be related to the passport or ipinfo cache.  Both modules cache promises of active requests (ip or passport lookups).
This issue feels like there's a never resolving promise in that cache, so everytime someone retries using the faucet with the same IP or address with such a bad cache entry will end up with a timeout.

I'm rreopening the issue as the underlying problem is not solved.
Debug output is still active, so, if anyone runs into a similar problem, please respond here soonish.

**Comment by deepmineblocks** [comment]
@pk910 

You did 3 commits, so I think the issue is resolved and I closed the issue 😊.

Good to know about some underlying things.

If you need any assistance/debug logs etc feel free to post here...

**Comment by pk910** [comment]
that's exactly the problem :D
I did not change anything that might had an effect on that issue. 
I've even reverted these commits again as the additional debug output heavily spams the logs..

However, to run the new code I've restarted the process, which kind of solved the problem for you two.
The underlying issue that caused the problem is still there :D

**Comment by Leooehh** [comment]
@pk910
I had a user who was facing this issue which odd enough they could access with no issues using a vpn..  My instance doesn't have passport enabled, I only have IP, Mainnet and captcha enabled. 
I hope this helps, cheers.

**Comment by pk910** [comment]
should be fixed with latest release, which is also rolled out to the public instances
